name: lando-mailhog
services:
  mailhog:
    type: mailhog
    hogfrom:
      - php
      - nginx
  php:
    type: php
  nginx:
    type: nginx:1.25

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mailhog": ../..
  "@lando/php": ../../node_modules/@lando/php
  "@lando/nginx": ../../node_modules/@lando/nginx

