name: lando-mailhog
services:
  mailhog:
    type: mailhog
    hogfrom:
      - php
  php:
    type: php

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mailhog": ./../../